eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
logging:
    pattern:
      console: "%d-%msg%n"
      file: F:\logs\server-logs\${spring.application.name}.log
    level:
        com.feima.xxhglcaseservice.dao: debug
server:
    port: 8091
    tomcat:
        uri-encoding: UTF-8
        max-http-post-size: 102400000
spring:
    application:
        name: resources-service
    datasource:
        name: demo_resources
        url: jdbc:mysql://localhost:3306/demo_resources?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 2
        maxWait: 60000
        minIdle: 2
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
        converters:
            preferred-json-mapper: jackson
        encoding:
            charset: UTF-8
            force: true
            enabled: true
        multipart:
          max-file-size: 1000Mb
          max-request-size: 1001Mb
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    mvc:
        date-format: yyyy-MM-dd HH:mm:ss
        favicon:
            enabled: true
        static-path-pattern: /**
mybatis:
  mapper-locations: classpath:mapping/*.xml
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql